// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqxqlnajziqqszjeyhdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xeHFsbmFqemlxcXN6amV5aGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDc2MjYsImV4cCI6MjA3MDQ4MzYyNn0.VxkLQ1v4o3oB41tGe3Rraa2m4Er0ZAKNELgf1KyHRsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});